/**
 * build-tokens.mjs
 * ----------------
 * Turns the design-system tokens (design/tokens.json) into CSS:
 *   src/styles/generated/tokens.css      → custom properties (colors per theme, spacing, radius, layout, fonts)
 *   src/styles/generated/typography.css  → one `.t-<style>` class per type style
 *
 * Never edit the generated files by hand. Change design/tokens.json, then run:
 *   npm run tokens
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(resolve(root, "design/tokens.json"), "utf8"));
const outDir = resolve(root, "src/styles/generated");
mkdirSync(outDir, { recursive: true });

const HEADER = `/* GENERATED by scripts/build-tokens.mjs from design/tokens.json. Do not edit. Run \`npm run tokens\`. */\n`;

// "{accent}" → "var(--accent)"
const resolveAlias = (v) => (typeof v === "string" && /^\{.+\}$/.test(v) ? `var(--${v.slice(1, -1)})` : v);
const valueFor = (token, themeId, firstTheme) => {
  const v = token.value;
  if (typeof v === "string") return themeId === firstTheme ? resolveAlias(v) : null; // theme-independent: declare once
  return v[themeId] !== undefined ? resolveAlias(v[themeId]) : null;
};
const decl = (name, value, usage) => `  --${name}: ${value};${usage ? ` /* ${usage.replace(/\*\//g, "")} */` : ""}`;

// ---------- tokens.css ----------
const themes = tokens.color.themes.map((t) => t.id);
const [first] = themes;
const colorScheme = { dark: "dark", light: "light" };
let css = HEADER;

for (const theme of themes) {
  const selector = theme === first ? `:root,\n[data-theme="${theme}"]` : `[data-theme="${theme}"]`;
  const lines = [`  color-scheme: ${colorScheme[theme] ?? "normal"};`];
  for (const t of tokens.color.tokens) {
    const v = valueFor(t, theme, first);
    if (v !== null) lines.push(decl(t.name, v));
  }
  for (const t of tokens.shadow?.tokens ?? []) {
    const v = valueFor(t, theme, first);
    if (v !== null) lines.push(decl(t.name, v));
  }
  css += `\n/* theme: ${theme} */\n${selector} {\n${lines.join("\n")}\n}\n`;
}

const scalar = [];
for (const family of ["spacing", "radius", "layout"]) {
  scalar.push(`  /* ${family} */`);
  for (const t of tokens[family]?.tokens ?? []) scalar.push(decl(t.name, t.value));
}
// Project hues also get a fixed "-dark" copy for surfaces that stay dark in every theme (code, terminal).
scalar.push("  /* project hues on always-dark surfaces */");
for (const t of tokens.color.tokens) {
  if (t.name.startsWith("hue-") && typeof t.value === "object") scalar.push(decl(`${t.name}-dark`, t.value[first]));
}
scalar.push("  /* font families */");
for (const [key, stack] of Object.entries(tokens.type.families)) scalar.push(decl(`font-${key}`, stack));
css += `\n:root {\n${scalar.join("\n")}\n}\n`;

writeFileSync(resolve(outDir, "tokens.css"), css);

// ---------- typography.css ----------
const kebab = (s) => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
let type = HEADER;
for (const group of tokens.type.groups) {
  type += `\n/* ${group.name} */\n`;
  for (const s of group.styles) {
    const props = { fontFamily: `var(--font-${s.family ?? group.family})` };
    for (const k of ["fontSize", "lineHeight", "fontWeight", "letterSpacing", "fontStyle"]) if (s[k] !== undefined) props[k] = s[k];
    if (s.name === "label") props.textTransform = "uppercase";
    const body = Object.entries(props).map(([k, v]) => `  ${kebab(k)}: ${v};`).join("\n");
    type += `/* ${s.usage ?? ""} */\n.t-${s.name} {\n${body}\n}\n`;
  }
}
writeFileSync(resolve(outDir, "typography.css"), type);

console.log(`tokens: ${tokens.color.tokens.length} colors × ${themes.length} themes → src/styles/generated/`);
